baseURL = "https://www.andrewmcdonough.com"
title = "Andrew McDonough"
theme = "PaperMod"
languageCode = "en-us"
paginate = 10
enableRobotsTXT = true

[services.googleAnalytics]
  ID = "G-GKLTCTS978"

[params]
  author = "Andrew McDonough"
  mainSections = ["posts", "talks"]
  description = "Andrew McDonough's Personal Website"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true

[[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/andrewmcdonough"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/andrewmcdonough"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/andrewmcdonough"

[params.homeInfoParams]
  Title = "Hi, I'm Andrew"
  Content = "I'm currently based in Berlin and working as CTO of CaptionHub."

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup.highlight]
  style = "monokai"

[markup.goldmark.renderer]
  unsafe = true

[permalinks]
  posts = "/:year/:month/:day/:slug/"
